version: '2.4'

services:
  webserver:
    #env_file: ./inputs.env
    platform: windows
    build: ./
    tty: true
    volumes:
      - type: bind
        source: ${{AppSource}}
        target: C:/PIWorks/Apps/AutoDeployer/shared_volume/
    environment: 
      username: ${{AppUsername}}
      password: ${{AppPassword}}
    networks: [grid]

  selenium-hub:
    image: selenium/hub
    platform: linux
    container_name: selenium-hub
    ports:
      - '${{SeleniumHubPort}}:4444'
    networks: [grid]
    
  chrome-debug:
    image: selenium/node-chrome-debug
    platform: linux
    depends_on:
      - selenium-hub
    ports:
      - '${{ChromePort}}:5900'
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks: [grid]

  chrome:
    image: selenium/node-chrome
    platform: linux
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

networks:
  grid:
    driver: nat